version: '3.8'

services:
  api:
    build: .
    container_name: fastapi-clean-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - MONGO_URI=${MONGO_URI}
    env_file:
      - .env
